### PR TITLE
Update OSGi manifest generation (#158)

### PR DESCRIPTION
**Pull request by fwolter**
The manifest looks more complete, now. @wborn can you test it with OpenHAB?

### CODE REVIEW

**Comment by madhephaestus** [comment]
i just pushed the latest binaries, you should be able to pull and try this locally with just a java build

**Comment by madhephaestus** [comment]
It looks like you will need to drop the Java 7 build in order to add OSGI

**Comment by madhephaestus** [comment]
I ran this and it produce a manafest with some strange line breaks in the manifest:

```
Manifest-Version: 1.0
Bnd-LastModified: 1586370308540
Bundle-ManifestVersion: 2
Bundle-Name: nrjavaserial
Bundle-SymbolicName: nrjavaserial
Bundle-Version: 3.18.0
Created-By: 11.0.6 (Ubuntu)
Implementation-Title: nrjavaserial
Implementation-Vendor: Commonwealth Robotics Cooperative
Implementation-Version: 3.18.0
Import-Package: com.sun.jna.platform.win32;resolution:=optional,org.ap
 ache.commons.net.telnet;resolution:=optional;version="[3.3,4)"
Private-Package: com.neuronrobotics.nrjavaserial,gnu.io,gnu.io.factory
 ,gnu.io.rfc2217,native.freebsd.x86_32,native.freebsd.x86_64,native.li
 nux.ARM_32,native.linux.ARM_64,native.linux.PPC,native.linux.x86_32,n
 ative.linux.x86_64,native.osx,native.windows.x86_32,native.windows.x8
 6_64
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"
Specification-Title: nrjavaserial
Specification-Vendor: Commonwealth Robotics Cooperative
Specification-Version: 3.18.0
Tool: Bnd-5.0.1.202003231327
```

**Comment by wborn** [comment]
Thanks for working on this! I'll give it a test with openHAB.

According to the spec lines in manifests should be wrapped at 72 chars:

https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html

> No line may be longer than 72 bytes (not characters), in its UTF8-encoded form. If a value would make the initial line longer than this, it should be continued on extra lines (each starting with a single SPACE).

**Comment by madhephaestus** [comment]
Here is a snapshot to test

[nrjavaserial-3.18.0.zip](https://github.com/NeuronRobotics/nrjavaserial/files/4452407/nrjavaserial-3.18.0.zip)

**Comment by wborn** [comment]
I didn't work, but after add an Export-Package line it does work! :+1: 
See these changes: https://github.com/fwolter/nrjavaserial/pull/1

**Pull request merged**
