### PR TITLE
Support serial dirvers lacking internal buffers

### PR DESCRIPTION
**Pull request by T-Svensson**
- On Windows, some serial drivers throws an error from tcdrain() as they claim that they have no buffers. Do not treat this as a fatal error, but instead assume that the write was successful and continue on.
- Do not hide the error message from tcdrain() when something goes wrong.
- Revert to RXTX API so NRJavaSerial can be used as a drop-in replacement for projects using gnu.io.* classes.
- Fixed some minor compilation warnings.

### CODE REVIEW

**Comment by madhephaestus** [comment]
Thanks! this looks good, but can you include the updated binaries? The self-extracting binaries is the most important part, and we do not yet have a fully automated build process.

**Comment by T-Svensson** [comment]
Is it enough if I provide updated 32- and 64-bit Windows DLL's or do you need a rebuild for every platform you support?

**Comment by madhephaestus** [comment]
since this issue only affects Windows, the 2 windows ones would be fine. Also, can you change back your changed to CommPortIdentifier? Its a public interface, so it should not be changed.

**Comment by T-Svensson** [comment]
Well, the change I did in CommPortIdentifer is one of the key changes to make it work with org.eclipse.tm.terminal, the terminal plugin provided by the Eclipse foundation.
RXTX, CommPortIdentifier.java line 352 in http://rxtx.qbang.org/pub/rxtx/rxtx-2.2pre2.zip, uses the return type CommPort thus NRJavaSerial broke the API when it changed. I can't see when the change happened, since github has no record of the source before commit f24084736c1cae1519df45138f4f3243c27db73d.

It's only the first point In the description that only affects Windows, the rest affects all the different platforms.

**Comment by T-Svensson** [comment]
Actually, I was wrong, GitHub do have the change on record in commit 058212eb692e0c52afa63cb78d142c0e53a56350. I think this commit was done by you some 5 years ago.

**Comment by madhephaestus** [comment]
Reopen if your branch is mergable

**Pull request closed without merging**
