### PR TITLE
Source directory cleanup

### LINKED ISSUE #38: Which is the main source directory now?
As of f24084736c1cae1519df45138f4f3243c27db73d, the source directory seems to be `src`, not `nrjavaserial/src`. But 14493a8cfe286f6dacb627179fa11ebfbf718200 was accepted as a change to `nrjavaserial/src`, and the Ant and Maven build files are still in the `nrjavaserial` directory. I can create a pull request to clean this up, but which do we want to use going forward: `src` or `nrjavaserial/src`?

### PR DESCRIPTION
**Pull request by MrDOS**
This pull request places all build system definitions in the source tree root, merges the binaries added in 14493a8cfe286f6dacb627179fa11ebfbf718200 into the `src/main/c/natives` directory, and nukes the `nrjavaserial` directory. If accepted, it closes #38.

@madhephaestus I won't merge this into master myself as I'd still like confirmation that I haven't misinterpreted what you moving towards with f24084736c1cae1519df45138f4f3243c27db73d.

### CODE REVIEW

**Comment by MrDOS** [comment]
@madhephaestus has resolved this with de06e99969c4a31498528ddc84dabc72d6c59812.

**Comment by madhephaestus** [comment]
oh, sorry, i didn't notice you were working on this. I hope i didn't mess you up too much. I also shifted the build to gradle moving forward, which is the only actual *change*.

**Comment by MrDOS** [comment]
Nah, it's OK. This had maintained support for Maven but Gradle's OK with me. I'm going to make another pull request in a few minutes that includes some documentation on how to kick off the Gradle build – a clean checkout of the repository is currently non-building for reasons which may not be immediately obvious to a casual bystander who just wants to make some simple tweaks to the code.

**Comment by madhephaestus** [comment]
cool, thanks! I also added the scripting for uploading the files to Maven Central. I will add the dummy AUTH file so the gradle build doesn't break...

**Comment by andyrozman** [comment]
Did you merge /c files too, because I think that new changes were lost... at least I think that Makefile is the old one...

**Comment by madhephaestus** [comment]
@andyrozman Good catch, grabbed that and pushed it forward. According to the history there shouldn't be anything else in the Cdir that is not in the correct build directory.

**Comment by andyrozman** [comment]
Mhm. Now all natives are gone... They should be under src/main/resources/native, or are they back where they were: src/main/c/resources/native... Where should they be... I found them on previous location (under src/main/c). Is this now intended location?

**Comment by MrDOS** [comment]
That was my doing in #41. Prior to that, we had the natives duplicated in two locations: `src/main/c/resources/native`, which is where freshly-built natives are placed by Make; and `src/main/resources/native`, which is where Gradle was looking but which was only updated by manual effort. There didn't seem to be any reason for the duplication, so I nuked the one which was easiest to remove. In retrospect, maybe I should have solicited other opinions first. Is `src/main/resources/native` that much more preferable? If it is, I could alter the makefile to put natives there.

**Comment by andyrozman** [comment]
I am not sure what is better for Gradle... 

Maven normally looks into src/main/resources, but I know that we had special lines in pom.xml, which told to look at src/main/c/resources... But I think that we changed Makefile in src/main/c to put it into src/main/resources or not?

**Comment by MrDOS** [comment]
I also had to modify `build.gradle` to look in `src/main/c/resources`. I can't see any traces of the Makefile having been modified to output to `src/main/resources`; the [Makefile from right after Gradle support was added](https://github.com/NeuronRobotics/nrjavaserial/blob/7da8beeef9ab8d956c9c6684df220d519cc76a7a/src/main/c/Makefile) still wanted to use `src/main/c/resources`.

I do agree, though, that convention says to use `src/main/resources`. I wanted to streamline the Makefile a bit for #19 anyway; maybe I will move it then (unless someone beats me to it, of course).

**Pull request closed without merging**
