### PR TITLE
Debug flags

### PR DESCRIPTION
**Pull request by heribender**
Hi

I implemented some enhancements/bugfixes:
-  dealing with the debug flags. Until now they were hardcoded, I added the possibility to define them by SysEnvVars. 
-- static method initDebugFlags added to CommPortIdentifier, RXTXCommDriver and RXTXPort
- Searching for gnu.io.rxtx.properties: EnvVar "java.ext.dirs" may return more than one dir
- build.gradle: 
-- added the possibility to overload the build.properties by a user.build.properties
-- introduced the new build property jar.noversion. If set to true, the built jar file does not contain a version.
- README.md enhanced: Added detailled description of the recognized environment variables starting with "gnu.io.".

I would love if you would merge this changes to the HEAD. 

BTW: I had to do the changes (and tests) on a branch of Version 3.12.1 (commit c9f9f84e434115739d6ee2565829761c60624752), because later commits contain changes which use forbidden java classes ("com.sun." package) which are not present in a java 8 JRE. You should re-evaluate these changes by finding another possibility to recognize the comports on windows system without the need of using these forbidden packages.

### CODE REVIEW

**Comment by madhephaestus** [comment]
Pull from master and merge the conflicts into this branch?

**Comment by heribender** [comment]
Yes. for my changes I branched the version 3.12.1 (commit c9f9f84). The conflicts are only in the import statements, nowhere in the code. Thus you can edit the conflicts by overtaking my version.

**Comment by heribender** [comment]
BTW: I would resolve it by myself, but I do not know how. Clicking on above "Resolve conflicts" button leads me to a page which only displays the conflicts, but does not allow to resolve it. Maybe because I have no write access to the main repo?

**Comment by madhephaestus** [comment]
Reopen if your branch is mergable

**Pull request closed without merging**
