### PR TITLE
Fix optional imports for OSGi

### PR DESCRIPTION
**Pull request by crea-doo**
Follow-up PR related to https://github.com/NeuronRobotics/nrjavaserial/pull/100.
Now the JNA dependency is really optional:
On Windows there is a check if the classes are present and if not available ports are detected using the old behaviour.

The RFC2217 functionality is unchanged and only needs the dependency present when a TelnetSerialPort ist instanciated (on all platforms).

### CODE REVIEW

**Comment by crea-doo** [comment]
The Travis buils is failing because the travis configuration is somehow broken:

- Travis doesn't support oraclejdk7 any more
- openjdk7 isn't able to start up the Gradle wrapper

I'll provide a fix...

**Comment by crea-doo** [comment]
Should be fixed in #110...

**Comment by msteigenberger** [comment]
+1
I'd need that change for my openhab binding.
Thanks!

**Comment by martinvw** [comment]
Hello what is the status here, is there anyone we can / should mention to increase the chances of it being merged?

**Comment by kaikreuzer** [comment]
@madhephaestus, We (meaning @eclipse SmartHome and @openhab projects) are heavily dependent on this fix - any chance to have it merged and do a new official release any time soon? 0.13.0 is already more than a year old, so it would be awesome if you could spend a little time to move this forward - thanks!

**Comment by madhephaestus** [comment]
now in 3.14.0, should be synced to Maven Central in a day or so

**Comment by martinvw** [comment]
@madhephaestus Thanks!

**Comment by kaikreuzer** [comment]
Excellent, many thanks!

**Comment by madhephaestus** [comment]
repositories {
	//com.neuronrobotics hosting point
	maven { url 'https://oss.sonatype.org/content/repositories/staging/' }
}
dependencies {
	compile "com.neuronrobotics:nrjavaserial:3.14.0"
}

for the impatient

**Pull request merged**
