### PR TITLE
Added FreeBSD make instructions to README.md

### PR DESCRIPTION
**Pull request by RafalLukawiecki**

### CODE REVIEW

**Comment by madhephaestus** [comment]
can you add some information to the readme on how to set up the compilation toolchain on Ubuntu to cross compile? I would like to keep all the binaries up to date on as best i can and would like it to run in CI

**Comment by RafalLukawiecki** [comment]
I would like to, but I am afraid I have never tried compiling FreeBSD on Ubuntu, and my knowledge of Ubuntu (and Linux) is limited. Could you point me to a generic example of doing that using a different OS, say Windows compilation on Ubuntu, so I can have a look and think?

I assume you know that FreeBSD is not a Linux but a Unix, and so has a different kernel. Its closest sibling is the Darwin kernel on macOS, which is also based on BSD Unix. I do not know if it is possible, therefor, to compile FreeBSD code on Ubuntu.

**Comment by madhephaestus** [comment]
well if your unfamiliar then i guess we can make this its own issue. Here are the generic instructions in case you are interested: https://marcelog.github.io/articles/cross_freebsd_compiler_in_linux.html

**Comment by RafalLukawiecki** [comment]
Thank you, I will have a read.

**Pull request merged**
